name = "boat-rv-guardian-webhooks"
main = "src/index.ts"
compatibility_date = "2024-03-20"
compatibility_flags = ["nodejs_compat"]

# [vars]
# FIREBASE_SERVICE_ACCOUNT = "..."
# LINKTAP_API_URL = "https://www.link-tap.com/api"
